### ISSUE TITLE
TypeError: urlopen() got multiple values for keyword argument 'body'

### ISSUE THREAD

**Issue by maruashok** [glumia/openload_dl#8]
Using Ubuntu 14.04 32 Bit
Latest Firefox & https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux32.tar.gz

Error is

Traceback (most recent call last):
  File "/usr/local/bin/openload-dl", line 95, in <module>
    browser=webdriver.Firefox(firefox_options=fox_opt)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 79, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 142, in request_encode_body
    **urlopen_kw)
TypeError: urlopen() got multiple values for keyword argument 'body'

**Comment by glumia** [comment]
From a quick search on google it looks like the problem is an old version of urllib3 installed on your system. 
Try to upgrade pip and then urllib3.

    sudo pip install -U pip
    sudo pip install -U urllib3

If this doesn't work you will probably have to install openload-dl in a virtual environment or upgrade Ubuntu to a newer version.

References:
- https://stackoverflow.com/questions/51686224/typeerror-urlopen-got-multiple-values-for-keyword-argument-body-while-execu
- https://github.com/python-telegram-bot/python-telegram-bot/issues/481
- https://github.com/kubernetes-client/python/issues/214
